### ISSUE TITLE
HorizontalPager not swiping pages with swipe gesture

### ISSUE THREAD

**Issue by XBlack97** [pratikksahu/JetPDFVue#1]
1st off...i appreciate your Good work

i've been able to implement the next into buttons, but the default swipe gesture that comes with Horizontal pager seems not to be working, I'm currently working on it but maybe you can check it out...

**Comment by pratikksahu** [comment]
The user swipe is disabled as of now because the zoom gesture was interfering with the swipe gesture. As of now I have decided to provide other modes to swipe through pages.
You can check HorizontalPager examples.

I will soon be writing a proper Readme. Thanks for using the library,happy to help :)

**Comment by XBlack97** [comment]
still the same after setting `userScrollEnabled = true`, took out the line (to let the default) and the swipe still don't work.

**Comment by pratikksahu** [comment]
You have to remove the pinchToZoom modifier from the image
