### ISSUE TITLE
文件刚加载完点击分享之后屏幕渲染的图片白屏？

### ISSUE THREAD

**Issue by liuhongjian0316** [pratikksahu/JetPDFVue#2]
android13
redmik40pro
文件刚加载完点击分享之后屏幕渲染的图片白屏， 出现白屏点下一页或其它渲染操作(渲染)后，再次点击分享就没有图片白屏的情况

**Comment by pratikksahu** [comment]
Can you share video/exact steps for this? I am not able to reproduce this issue

**Comment by liuhongjian0316** [comment]
https://github.com/pratikksahu/JetPDFVue/assets/45460278/399573db-5abc-4ab8-803e-0de882fed86e

**Comment by pratikksahu** [comment]
Unfortunately I was not able to reproduce because the share screen view is different in my device and my old test device.
The white screen is due to the bitmap being disposed.
[HorizontalVueReader.kt](JetPDFVue/src/main/java/com/pratikk/jetpdfvue/HorizontalVueReader.kt)
```kotlin
DisposableEffect(key1 = Unit) {
                    vueRenderer.pageLists[idx].load()
                    onDispose {
                        vueRenderer.pageLists[idx].recycle()
                    }
                }
```
Here you can see the bitmap is getting recycled. To avoid this, you can use cache param while creating the reader state like this
```kotlin
rememberHorizontalVueReaderState(
            resource = VueResourceType.Local(
                uri = uri,
                fileType = uri.getFileType(context)
            ),
            cache = 2
        )
```
When using cache , the bitmap is recycled only when page is changed.
Please let me know if this solves your issur

**Comment by liuhongjian0316** [comment]
how to render  once again ?

**Comment by pratikksahu** [comment]
Did you creating reader like this?
‘’’kotlin
rememberHorizontalVueReaderState(
            resource = VueResourceType.Local(
                uri = uri,
                fileType = uri.getFileType(context)
            ),
            cache = 2
        )
‘’’
